export type VideoErrorCode =
  | 'VALIDATION_FAILED'
  | 'NOT_VIDEO_OWNER'
  | 'VIDEO_NOT_FOUND'
  | 'LESSON_ALREADY_HAS_VIDEO'
  | 'INVALID_VIDEO_STATE'
  | 'UPLOAD_OBJECT_MISSING'
  | 'UPLOAD_OBJECT_SIZE_MISMATCH'
  | 'INTERNAL';
