export type AuthErrorCode =
  | 'INVALID_EMAIL'
  | 'WEAK_PASSWORD'
  | 'INVALID_DISPLAY_NAME'
  | 'EMAIL_ALREADY_EXISTS'
  | 'INVALID_ID_TOKEN'
  | 'RECENT_SIGN_IN_REQUIRED'
  | 'UNAUTHENTICATED'
  | 'INTERNAL';
