export const PICTURE_ERROR_CODES = [
  'PROFILE_PICTURE_DIMENSIONS_TOO_SMALL',
  'PROFILE_PICTURE_DECODE_FAILED',
  'PROFILE_PICTURE_TOO_LARGE',
  'UNSUPPORTED_PROFILE_PICTURE_FORMAT',
] as const;

export type PictureErrorCode = (typeof PICTURE_ERROR_CODES)[number];
