export type CoursesErrorCode =
  | 'VALIDATION_FAILED'
  | 'NOT_COURSE_OWNER'
  | 'COURSE_NOT_FOUND'
  | 'MODULE_NOT_FOUND'
  | 'LESSON_NOT_FOUND'
  | 'STALE_REORDER'
  | 'INVALID_TRANSITION'
  | 'PUBLISH_NOT_ELIGIBLE'
  | 'COURSE_ARCHIVED'
  | 'COURSE_NOT_AVAILABLE'
  | 'CANNOT_ENROLL_OWN_COURSE'
  | 'NOT_ENROLLED'
  | 'INTERNAL';
