import { type ClassValue, clsx } from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

// Teaches tailwind-merge the design-system's custom `@theme` keys so conflicting
// utilities collapse to last-wins. `color` registration also disambiguates the
// overloaded `text-` prefix (color vs font-size). Mirrors the `@theme inline`
// block in apps/web/src/tailwind.css — cn.spec.ts is the drift guard.
const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      // Stryker disable next-line ArrayDeclaration: equivalent — tailwind-merge v3's default color scale accepts any value, so custom color names conflict-resolve (bg-/text-/border-) even with this list emptied; the registration documents the DS palette rather than changing merge behavior (verified empirically)
      color: [
        // lw core palette
        'bg',
        'bg-2',
        'bg-3',
        'line',
        'line-2',
        'ink',
        'ink-2',
        'ink-3',
        'ink-4',
        'ochre',
        'ochre-2',
        'ochre-ink',
        'ochre-soft',
        'moss',
        'clay',
        'rust',
        'good',
        'warn',
        'bad',
        // shadcn-compat semantic aliases
        'background',
        'foreground',
        'muted',
        'muted-foreground',
        'surface',
        'surface-raised',
        'surface-sunken',
        'surface-hover',
        'surface-active',
        'border',
        'border-subtle',
        'border-strong',
        'border-hover',
        'border-focus',
        'primary',
        'primary-soft',
        'primary-strong',
        'primary-foreground',
        'primary-hover',
        'primary-hover-foreground',
        'primary-active',
        'primary-active-foreground',
        'primary-disabled',
        'primary-disabled-foreground',
        'secondary',
        'secondary-foreground',
        'accent',
        'accent-foreground',
        'success',
        'success-foreground',
        'warning',
        'warning-foreground',
        'destructive',
        'destructive-foreground',
        'info',
        'info-foreground',
        'ring',
        // form field roles
        'input',
        'input-disabled',
        'input-border',
        'input-border-hover',
        'input-border-focus',
        'input-border-invalid',
        'input-placeholder',
        'checkbox-bg',
        'field-helper',
        'field-helper-invalid',
        // list/table roles
        'list-row-bg-hover',
        'list-row-bg-selected',
        'list-row-bg-selected-hover',
        'list-header-bg',
        'list-header-border',
        'list-cell-border',
        // overlay
        'scrim',
        'dialog',
        'dialog-border',
        'dialog-foreground',
        'popover',
        'popover-border',
        'popover-foreground',
        'overlay-select-bg',
        'overlay-select-border',
        'overlay-select-fg',
        'tooltip-bg',
        'tooltip-fg',
        // content surfaces
        'card',
        'card-hover',
        'card-foreground',
        'card-foreground-hover',
        'card-foreground-muted',
        // selection
        'selection-bg',
        'selection-bg-hover',
        'selection-fg',
        // nav item
        'nav-item-bg-hover',
        'nav-item-bg-selected',
        'nav-item-fg',
        'nav-item-fg-hover',
        'nav-item-fg-selected',
        'nav-item-icon',
        'nav-item-icon-hover',
        // button — 5 variants
        'button-primary-bg',
        'button-primary-bg-hover',
        'button-primary-bg-active',
        'button-primary-fg',
        'button-primary-fg-hover',
        'button-primary-fg-active',
        'button-primary-border',
        'button-primary-border-hover',
        'button-secondary-bg',
        'button-secondary-bg-hover',
        'button-secondary-bg-active',
        'button-secondary-fg',
        'button-secondary-border',
        'button-secondary-border-hover',
        'button-ghost-bg-hover',
        'button-ghost-bg-active',
        'button-ghost-fg',
        'button-ghost-fg-hover',
        'button-link-fg',
        'button-link-fg-hover',
        'button-danger-bg',
        'button-danger-bg-hover',
        'button-danger-fg',
        'button-danger-fg-hover',
        'button-danger-border',
        // badge — 7 hue families
        'badge-neutral-bg',
        'badge-neutral-fg',
        'badge-accent-bg',
        'badge-accent-fg',
        'badge-info-bg',
        'badge-info-fg',
        'badge-success-bg',
        'badge-success-fg',
        'badge-warn-bg',
        'badge-warn-fg',
        'badge-danger-bg',
        'badge-danger-fg',
        'badge-category-bg',
        'badge-category-fg',
        'badge-info-border',
        'badge-success-border',
        'badge-warn-border',
        'badge-danger-border',
        'badge-category-border',
      ],
      radius: ['control', 'nav-item', 'badge', 'tooltip'],
      // Stryker disable next-line ArrayDeclaration, StringLiteral: equivalent — tailwind-merge v3's default shadow scale accepts any value, so shadow-* names conflict-resolve even with this list emptied (verified empirically: shadow-raised/shadow-overlay merge with no registration at all)
      shadow: ['1', '2', 'raised', 'overlay', 'dialog'],
      // No named t-shirt spacing scale here (donor's xs..xl / cell-* were not
      // ported — Learn Wren keeps Tailwind's numeric spacing scale).
      spacing: [
        'control-x',
        'control-y',
        'control-x-sm',
        'control-y-sm',
        'control-x-lg',
        'control-y-lg',
        'control-gap',
        'nav-item-x',
        'nav-item-y',
        'nav-item-gap',
        'badge-x',
        'badge-y',
        'badge-gap',
        'tooltip-x',
        'tooltip-y',
        'form-field-gap',
        'form-row-gap',
        'form-section-gap',
      ],
      text: [
        'page-title',
        'section-title',
        'field-label',
        'body',
        'helper',
        'code',
      ],
    },
    classGroups: {
      z: [
        {
          z: [
            'base',
            'sticky',
            'sticky-elevated',
            'dropdown',
            'popover',
            'dialog-backdrop',
            'dialog',
            'toast',
          ],
        },
      ],
    },
  },
});

/** Class composer for `@learnwren/web-ui`: joins names (clsx) and resolves Tailwind conflicts (twMerge). */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
