#!/usr/bin/env tsx
/**
 * Generates apps/web/src/environments/environment.ts from the current process
 * environment. Always overwrites. Idempotent in emulator mode.
 *
 * Inputs (env):
 *   LEARNWREN_FIREBASE_TARGET                'emulator' | 'production' (default 'emulator')
 *
 * Required only when target=production:
 *   LEARNWREN_WEB_FIREBASE_API_KEY
 *   LEARNWREN_WEB_FIREBASE_AUTH_DOMAIN
 *   LEARNWREN_WEB_FIREBASE_PROJECT_ID
 *   LEARNWREN_WEB_FIREBASE_APP_ID
 *   LEARNWREN_WEB_FIREBASE_STORAGE_BUCKET
 *   LEARNWREN_WEB_FIREBASE_MESSAGING_SENDER_ID
 *
 * Output shape: Environment from ../../apps/web/src/environments/firebase-target.ts.
 * Emulator-mode output carries `emulatorHosts`; production-mode output omits
 * the field entirely so the production bundle ships no emulator strings.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { firebaseTargetMode } from '../../apps/web/src/environments/firebase-target.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');
const OUTPUT_PATH = resolve(REPO_ROOT, 'apps/web/src/environments/environment.ts');

const EMULATOR_PROJECT_ID = 'demo-learnwren';

const EMULATOR_HOSTS = {
  auth:      'http://127.0.0.1:9099',
  firestore: { host: '127.0.0.1', port: 8080 },
  storage:   { host: '127.0.0.1', port: 9199 },
} as const;

interface FirebaseConfig {
  apiKey?: string;
  authDomain?: string;
  projectId: string;
  appId?: string;
  storageBucket?: string;
  messagingSenderId?: string;
}

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `[build-environment] LEARNWREN_FIREBASE_TARGET=production requires ${name} to be set.`,
    );
  }
  return value;
}

function buildConfig(mode: 'emulator' | 'production'): FirebaseConfig {
  if (mode === 'emulator') {
    return { projectId: EMULATOR_PROJECT_ID };
  }
  return {
    apiKey:            required('LEARNWREN_WEB_FIREBASE_API_KEY'),
    authDomain:        required('LEARNWREN_WEB_FIREBASE_AUTH_DOMAIN'),
    projectId:         required('LEARNWREN_WEB_FIREBASE_PROJECT_ID'),
    appId:             required('LEARNWREN_WEB_FIREBASE_APP_ID'),
    storageBucket:     required('LEARNWREN_WEB_FIREBASE_STORAGE_BUCKET'),
    messagingSenderId: required('LEARNWREN_WEB_FIREBASE_MESSAGING_SENDER_ID'),
  };
}

function render(mode: 'emulator' | 'production', config: FirebaseConfig): string {
  const valueLiteral =
    mode === 'emulator'
      ? `{
  firebaseTargetMode: 'emulator',
  firebase: ${JSON.stringify(config, null, 2)},
  emulatorHosts: ${JSON.stringify(EMULATOR_HOSTS, null, 2)},
}`
      : `{
  firebaseTargetMode: 'production',
  firebase: ${JSON.stringify(config, null, 2)},
}`;

  return `// AUTO-GENERATED by tools/web/build-environment.ts. Do NOT commit.
// Regenerate with: pnpm exec nx run web:generate-environment
// Source of truth: tools/web/build-environment.ts + the LEARNWREN_* env vars.

import type { Environment } from './firebase-target';

export const environment: Environment = ${valueLiteral};
`;
}

function main(): void {
  const mode = firebaseTargetMode(process.env['LEARNWREN_FIREBASE_TARGET']);
  const config = buildConfig(mode);
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, render(mode, config), 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[build-environment] wrote ${OUTPUT_PATH} (mode=${mode})`);
}

main();
