export type MaterialErrorCode =
  | 'VALIDATION_FAILED'
  | 'UNSUPPORTED_MATERIAL_TYPE'
  | 'MATERIAL_NOT_FOUND'
  | 'NOT_MATERIAL_OWNER'
  | 'INVALID_MATERIAL_STATE'
  | 'UPLOAD_OBJECT_MISSING'
  | 'UPLOAD_OBJECT_SIZE_MISMATCH'
  | 'INTERNAL';
